apiVersion: apps/v1
kind: Deployment
metadata:
  name: peliculas-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peliculas-db
  template:
    metadata:
      labels:
        app: peliculas-db
    spec:
      containers:
        - name: peliculas-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "peliculas_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: peliculas-db-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-db-script-volume
      volumes:
        - name: peliculas-db-storage
          persistentVolumeClaim:
            claimName: peliculas-db-pvc
        - name: init-db-script-volume
          configMap:
            name: init-db-script
