apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peliculas-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Deberás ajustar esto según tus necesidades
